# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
    - job: Firstjob
      steps:
      - bash: echo Hello, first job
      - bash: echo $(pipelinevariable)
      - bash: echo $(Build.Buildnumber)
      - bash: echo $(Build.Buildid)
      - bash: echo $(Build.ArtifactStagingDirectory)
      - bash: Java -version
      - bash: python --version
      - bash: mvn -version
      - bash: ls -R $(Build.ArtifactStagingDirectory)
      - task: CopyFiles@2
        inputs:
          SourceFolder: '$(System.DefaultWorkingDirectory)'
          Contents: '**/*.yaml'
          TargetFolder: '$(Build.ArtifactStagingDirectory)'
      - bash: ls -R $(Build.ArtifactStagingDirectory)
#     - job: secondjob
#       steps:
#       - bash: echo Hello, first job!
# - stage: Devdeploy
#   variables:
#     environment: dev
#   jobs:
#     - job: Devdeployjob
#       steps:
#       - bash: echo $(environment)deploy job
# - stage: QAdeploy
#   variables:
#     environment: QA
#   jobs:
#     - job: QAdeployjob
#       steps:
#       - bash: echo $(environment)deploy job
# - stage: Proddeploy
#   variables:
#     environment: prod
#   dependsOn:
#   - Devdeploy
#   - QAdeploy
#   jobs:
#     - job: Proddeployjob
#       steps:
#       - bash: echo $(environment)deploy job