trigger:
- master

# # strategy:
#   matrix:
#     linux:
#       operatingSystem: 'ubuntu-latest'
#     mac:
#       operatingSystem: 'macos-latest'

pool:
  vmImage: 'ubuntu-latest'

stages: 
- stage: build
  jobs:
  - job: buildjob
    steps:
    - bash: echo "do the build"
- stage: devdeployjob
  jobs:
  - deployment: devdeployjob
    environment: dev
    strategy:
      runOnce:
        deploy:
          steps:
            - script: echo deploy to dev
- stage: devdeployjob
  jobs:
  - deployment: devdeployjob
    environment: QA
    strategy:
      runOnce:
        deploy:
          steps:
            - script: echo deploy to dev
